CREATE DATABASE IF NOT EXISTS helpdesk_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE helpdesk_db;

CREATE TABLE IF NOT EXISTS SOLICITANTES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NULL,
    setor VARCHAR(100) NOT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORIAS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TECNICOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CHAMADOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descricao TEXT NOT NULL,
    prioridade ENUM('BAIXA', 'MEDIA', 'ALTA') NOT NULL DEFAULT 'MEDIA',
    status ENUM('ABERTO', 'EM_ATENDIMENTO', 'CONCLUIDO') NOT NULL DEFAULT 'ABERTO',
    solucao TEXT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    solicitante_id INT NOT NULL,
    categoria_id INT NOT NULL,
    tecnico_id INT NULL,
    CONSTRAINT fk_chamados_solicitante
        FOREIGN KEY (solicitante_id) REFERENCES SOLICITANTES(id),
    CONSTRAINT fk_chamados_categoria
        FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id),
    CONSTRAINT fk_chamados_tecnico
        FOREIGN KEY (tecnico_id) REFERENCES TECNICOS(id),
    INDEX idx_chamados_status (status),
    INDEX idx_chamados_prioridade (prioridade),
    INDEX idx_chamados_criado_em (criado_em)
) ENGINE=InnoDB;
